=== bijington/Mobile.BuildTools/docs/schemas/v2/buildtools.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "id": "https://mobilebuildtools.com/schemas/v2/buildtools.schema.json",
  "title": "Mobile.BuildTools Project Configuration",
  "description": "Configures the Mobile.BuildTools. This file should generally be located next to the Solution file and be a central configuration for the entire solution.",
  "definitions": {
    "AppConfig": {
      "type": [
        "object",
        "null"
      ],
      "properties": {
        "disable": {
          "description": "Disables this Mobile.Build.Tools Task",
          "type": [ "boolean", "null" ],
          "default": false
        },
        "strategy": {
          "enum": [
            "TransformOnly",
            "BundleAll",
            "BundleNonStandard"
          ],
          "default": "TransformOnly",
          "description": "Defines how we should determine which app.config's to include. By default we only bundle the transformed app.config"
        }
      }
    },
    "ArtifactCopy": {
      "type": [
        "object",
        "null"
      ],
      "properties": {
        "disable": {
          "description": "Disables this Mobile.Build.Tools Task",
          "type": [ "boolean", "null" ],
          "default": false
        }
      }
    },
    "AutomaticVersioning": {
      "type": [
        "object",
        "null"
      ],
      "properties": {
        "behavior": {
          "description": "Configures whether the Versioning should prefer to use a Build Number or a Timestamp.",
          "default": "PreferBuildNumber",
          "enum": [
            "PreferBuildNumber",
            "Timestamp"
          ]
        },
        "environment": {
          "description": "Configures whether Versioning should occur only on a CI Host, Local Builds or anywhere.",
          "default": "All",
          "enum": [
            "All",
            "BuildHost",
            "Local"
          ]
        },
        "versionOffset": {
          "type": [ "integer", "null" ],
          "default": 0
        },
        "disable": {
          "description": "Disables this Mobile.Build.Tools Task",
          "type": [ "boolean", "null" ],
          "default": false
        }
      }
    },
    "ImageResize": {
      "type": [
        "object",
        "null"
      ],
      "properties": {
        "directories": {
          "description": "A list of search directories relative to this file",
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": [
              "string",
              "null"
            ]
          },
          "default": [
            "Images"
          ]
        },
        "conditionalDirectories": {
          "description": "A list of conditional search directories relative to this file. Supports build Configuration, monoandroid, or xamarin.ios",
          "type": [
            "object",
            "null"
          ],
          "additionalProperties": {
            "type": [
              "array",
              "null"
            ],
            "items": {
              "type": [
                "string",
                "null"
              ]
            }
          },
          "default": {
            "Xamarin.iOS": [ "Images/iOS" ],
            "MonoAndroid": [ "Images/Android" ],
            "Debug": [ "Images/Dev" ]
          }
        },
        "watermarkOpacity": {
          "description": "Configures the opacity to use for any watermark files (0 - 1)",
          "type": [
            "number",
            "null"
          ],
          "default": 0.95
        },
        "disable": {
          "description": "Disables this Mobile.Build.Tools Task",
          "type": [ "boolean", "null" ],
          "default": false
        }
      }
    },
    "ReleaseNotesOptions": {
      "type": [
        "object",
        "null"
      ],
      "properties": {
        "maxDays": {
          "description": "The number of days back to look when generating the Release Notes",
          "type": "integer",
          "default": 10
        },
        "maxCommit": {
          "description": "The maximum number of commits to lookup",
          "type": "integer",
          "default": 10
        },
        "characterLimit": {
          "description": "The maximum character limit for generated Release Notes",
          "type": "integer",
          "default": 250
        },
        "filename": {
          "description": "The output filename such as `ReleaseNotes.md` or `ReleaseNotes.txt`",
          "type": [
            "string",
            "null"
          ],
          "default": "releasenotes.txt"
        },
        "createInRoot": {
          "type": "boolean",
          "description": "If true it will create the Release Notes in the Solution Directory. Otherwise it will be created in the Project Directory.",
          "default": true
        },
        "disable": {
          "description": "Disables this Mobile.Build.Tools Task",
          "type": [ "boolean", "null" ],
          "default": false
        }
      }
    },
    "SecretsConfig": {
      "type": [
        "object",
        "null"
      ],
      "properties": {
        "disable": {
          "description": "Disables this Mobile.Build.Tools Task",
          "type": [ "boolean", "null" ],
          "default": false
        },
        "delimiter": {
          "description": "The delimiter used to separate values into an array. (i.e. ';' value1;value2)",
          "type": [
            "string",
            "null"
          ],
          "default": ";"
        },
        "prefix": {
          "type": [
            "string",
            "null"
          ]
        },
        "className": {
          "type": [
            "string",
            "null"
          ],
          "default": "Secrets"
        },
        "namespace": {
          "type": [
            "string",
            "null"
          ],
          "default": "Helpers"
        },
        "properties": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/ValueConfig"
          }
        }
      },
      "required": [
        "properties"
      ]
    },
    "TemplatedManifest": {
      "type": [
        "object",
        "null"
      ],
      "properties": {
        "token": {
          "type": [
            "string",
            "null"
          ],
          "default": "$$"
        },
        "variablePrefix": {
          "type": [
            "string",
            "null"
          ],
          "default": "Manifest_"
        },
        "missingTokensAsErrors": {
          "type": [ "boolean", "null" ],
          "default": false
        },
        "disable": {
          "description": "Disables this Mobile.Build.Tools Task",
          "type": [ "boolean", "null" ],
          "default": false
        }
      }
    },
    "ValueConfig": {
      "type": [
        "object",
        "null"
      ],
      "properties": {
        "name": {
          "description": "The name of the Property that will be generated",
          "type": [
            "string",
            "null"
          ]
        },
        "type": {
          "description": "The property type (i.e. string, int, DateTime)",
          "enum": [
            "String",
            "Bool",
            "Byte",
            "SByte",
            "Char",
            "Decimal",
            "Double",
            "Float",
            "Int",
            "UInt",
            "Long",
            "ULong",
            "Short",
            "UShort",
            "DateTime",
            "DateTimeOffset",
            "Guid",
            "Uri",
            "TimeSpan"
          ],
          "default": "String"
        },
        "isArray": {
          "description": "Flag to indicate whether to generate the property as an Array",
          "type": "boolean",
          "default": false
        }
      },
      "required": [
        "name",
        "type"
      ]
    },
    "XamarinCss": {
      "type": [
        "object",
        "null"
      ],
      "properties": {
        "disable": {
          "description": "Disables this Mobile.Build.Tools Task",
          "type": [ "boolean", "null" ],
          "default": false
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "appConfig": {
      "$ref": "#/definitions/AppConfig"
    },
    "artifactCopy": {
      "$ref": "#/definitions/ArtifactCopy"
    },
    "automaticVersioning": {
      "$ref": "#/definitions/AutomaticVersioning"
    },
    "css": {
      "$ref": "#/definitions/XamarinCss"
    },
    "images": {
      "$ref": "#/definitions/ImageResize"
    },
    "manifests": {
      "$ref": "#/definitions/TemplatedManifest"
    },
    "releaseNotes": {
      "$ref": "#/definitions/ReleaseNotesOptions"
    },
    "projectSecrets": {
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": {
        "$ref": "#/definitions/SecretsConfig"
      }
    },
    "debug": {
      "type": "boolean"
    }
  }
}

=== bijington/Mobile.BuildTools/sandbox/buildtools.json
{
  "$schema": "https://mobilebuildtools.com/schemas/v2/buildtools.schema.json",
  "appConfig": {
    "strategy": "BundleAll"
  },
  "artifactCopy": {
    "disable": true
  },
  "automaticVersioning": {
    "behavior": "PreferBuildNumber",
    "environment": "All",
    "versionOffset": 0
  },
  "images": {
    "directories": [
      "images"
    ]
  },
  "manifests": {
    "token": "$",
    "variablePrefix": "Manifest_",
    "missingTokensAsErrors": false,
    "disable": false
  },
  "releaseNotes": {
    "disable": true
  },
  "projectSecrets": {
    "FormsDemo": {
      "properties": [
        {
          "name": "SampleString",
          "type": "String",
          "isArray": false
        },
        {
          "name": "SampleBool",
          "type": "Bool",
          "isArray": false
        },
        {
          "name": "SampleInt",
          "type": "Int",
          "isArray": false
        },
        {
          "name": "SampleDouble",
          "type": "Double",
          "isArray": false
        },
        {
          "name": "SampleUri",
          "type": "String",
          "isArray": false
        }
      ]
    }
  }
}
